package sfx

import (
	"bytes"
	_ "embed"
	"errors"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gorm.io/gorm"

	"ridgericetalk/internal/model"
)

// Preset sounds ship embedded in the binary and are seeded into the library on startup.
// They belong to the reserved "system" user, are available to everyone, and cannot be deleted.
//
// The pack is generated by dev-scripts/assets/gen-sfx-presets (see that program's header
// for the design rationale). Every sound is a short rising or falling chime in the style
// of the default packs shipped by Discord / KOOK / Oopz / TeamSpeak: a two-note interval,
// soft attack, fast exponential decay, no harsh transients.

//go:embed presets/tone-up.mp3
var presetToneUp []byte

//go:embed presets/bell.mp3
var presetBell []byte

//go:embed presets/chord.mp3
var presetChord []byte

//go:embed presets/pluck-up.mp3
var presetPluckUp []byte

//go:embed presets/tone-down.mp3
var presetToneDown []byte

//go:embed presets/fall-soft.mp3
var presetFallSoft []byte

//go:embed presets/low-down.mp3
var presetLowDown []byte

//go:embed presets/pluck-down.mp3
var presetPluckDown []byte

// presetSound describes one embedded preset sound.
type presetSound struct {
	id       string // stable ID so re-seeding is idempotent
	title    string
	filename string
	data     []byte
	duration int // seconds (display only)
}

// presetUserID is the reserved owner ID for built-in preset sounds.
const presetUserID = "system"

// presets is the catalog of built-in sounds, in display order.
//
// The ordering is deliberate: the two-tone pair first (the plainest, most familiar
// gesture), then the bell, pad and pluck variants. The titles are symmetric
// (rising for the ones that read as an entrance, falling for an exit), but any
// preset can be bound to either the join or the leave slot.
//
// ListSounds orders presets by created_at DESC, so SeedPresets stamps them with
// descending timestamps — see presetOrderBase. Keep the slice order meaningful.
var presets = []presetSound{
	{id: "preset-tone-up", title: "清亮上行", filename: "tone-up.mp3", data: presetToneUp, duration: 1},
	{id: "preset-tone-down", title: "柔和下行", filename: "tone-down.mp3", data: presetToneDown, duration: 1},
	{id: "preset-bell", title: "清脆铃音", filename: "bell.mp3", data: presetBell, duration: 1},
	{id: "preset-chord", title: "温润和弦", filename: "chord.mp3", data: presetChord, duration: 1},
	{id: "preset-fall-soft", title: "温和下沉", filename: "fall-soft.mp3", data: presetFallSoft, duration: 1},
	{id: "preset-low-down", title: "低沉收束", filename: "low-down.mp3", data: presetLowDown, duration: 1},
	{id: "preset-pluck-up", title: "明亮弹拨", filename: "pluck-up.mp3", data: presetPluckUp, duration: 1},
	{id: "preset-pluck-down", title: "轻快回弹", filename: "pluck-down.mp3", data: presetPluckDown, duration: 1},
}

// SeedPresets brings the on-disk preset files and their DB rows in line with the
// embedded catalog. It is idempotent and self-healing:
//
//   - a missing or outdated file is (re)written from the embedded copy;
//   - a missing (or soft-deleted) row is inserted;
//   - an existing row whose title/path/duration drifted is refreshed in place, so
//     user bindings to that preset keep working across pack revisions;
//   - presets that are no longer in the catalog are removed outright, together with
//     every user binding and favorite that referenced them (otherwise those users
//     would keep a dangling "已失效" entry).
func (s *Service) SeedPresets() {
	dir := filepath.Join(s.cfg.LocalDataPath, "uploads", "sounds", "presets")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Printf("[sfx] seed presets: mkdir %s failed: %v", dir, err)
		return
	}
	keep := make(map[string]struct{}, len(presets))
	for i, p := range presets {
		keep[p.id] = struct{}{}
		// Descending timestamps so ListSounds' "created_at DESC" yields catalog order.
		s.seedPreset(dir, p, presetOrderBase.Add(-time.Duration(i)*time.Second))
	}
	s.prunePresets(dir, keep)
}

// presetOrderBase anchors the created_at values assigned to presets. Indices are
// subtracted from it (see SeedPresets), so the first catalog entry is the newest.
var presetOrderBase = time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC)

// seedPreset writes one preset to disk and upserts its library row.
func (s *Service) seedPreset(dir string, p presetSound, createdAt time.Time) {
	absPath := filepath.Join(dir, p.filename)
	if !fileMatches(absPath, p.data) {
		if err := os.WriteFile(absPath, p.data, 0644); err != nil {
			log.Printf("[sfx] seed preset %s: write failed: %v", p.id, err)
			return
		}
	}

	relPath, err := filepath.Rel(s.cfg.LocalDataPath, absPath)
	if err != nil || strings.HasPrefix(relPath, "..") {
		relPath = absPath
	}

	var row model.UserSound
	err = s.db.Unscoped().Where("id = ?", p.id).First(&row).Error
	switch {
	case errors.Is(err, gorm.ErrRecordNotFound):
		row = model.UserSound{
			ID:        p.id,
			UserID:    presetUserID,
			Title:     p.title,
			FilePath:  relPath,
			FileSize:  int64(len(p.data)),
			MimeType:  "audio/mpeg",
			Duration:  p.duration,
			IsPreset:  true,
			CreatedAt: createdAt,
		}
		if err := s.db.Create(&row).Error; err != nil {
			log.Printf("[sfx] seed preset %s: db create failed: %v", p.id, err)
		}
	case err != nil:
		log.Printf("[sfx] seed preset %s: db lookup failed: %v", p.id, err)
	default:
		// Refresh in place. Unscoped so a row that somehow got soft-deleted is
		// restored rather than duplicated under the same primary key.
		updates := map[string]any{
			"user_id":    presetUserID,
			"title":      p.title,
			"file_path":  relPath,
			"file_size":  int64(len(p.data)),
			"mime_type":  "audio/mpeg",
			"duration":   p.duration,
			"is_preset":  true,
			"created_at": createdAt,
			"deleted_at": nil,
		}
		if err := s.db.Unscoped().Model(&model.UserSound{}).Where("id = ?", p.id).Updates(updates).Error; err != nil {
			log.Printf("[sfx] seed preset %s: db update failed: %v", p.id, err)
		}
	}
}

// prunePresets removes built-in presets that are no longer part of the catalog,
// along with anything that pointed at them.
func (s *Service) prunePresets(dir string, keep map[string]struct{}) {
	var existing []model.UserSound
	if err := s.db.Unscoped().Where("is_preset = ?", true).Find(&existing).Error; err != nil {
		log.Printf("[sfx] prune presets: query failed: %v", err)
		return
	}
	// Resolve the presets directory once so a stale row can never make us delete a
	// user's own upload (only files inside the preset directory are removed).
	keepDir, _ := filepath.Abs(dir)
	for _, sd := range existing {
		if _, ok := keep[sd.ID]; ok {
			continue
		}
		// Hard delete: presets are seeded state, not user data, and leaving a
		// soft-deleted row behind would resurrect the dangling reference problem.
		if err := s.db.Unscoped().Delete(&model.UserSound{}, "id = ?", sd.ID).Error; err != nil {
			log.Printf("[sfx] prune preset %s: delete failed: %v", sd.ID, err)
			continue
		}
		if err := s.db.Model(&model.UserSoundSettings{}).
			Where("join_sound_id = ?", sd.ID).Update("join_sound_id", nil).Error; err != nil {
			log.Printf("[sfx] prune preset %s: clear join bindings failed: %v", sd.ID, err)
		}
		if err := s.db.Model(&model.UserSoundSettings{}).
			Where("leave_sound_id = ?", sd.ID).Update("leave_sound_id", nil).Error; err != nil {
			log.Printf("[sfx] prune preset %s: clear leave bindings failed: %v", sd.ID, err)
		}
		if err := s.db.Where("sound_id = ?", sd.ID).Delete(&model.UserSoundFavorite{}).Error; err != nil {
			log.Printf("[sfx] prune preset %s: clear favorites failed: %v", sd.ID, err)
		}
		if abs, err := filepath.Abs(s.absPath(sd.FilePath)); err == nil &&
			strings.HasPrefix(abs, keepDir+string(filepath.Separator)) {
			if err := os.Remove(abs); err != nil && !os.IsNotExist(err) {
				log.Printf("[sfx] prune preset %s: remove file %s failed: %v", sd.ID, abs, err)
			}
		}
		log.Printf("[sfx] pruned retired preset %s (%s)", sd.ID, sd.Title)
	}
}

// fileMatches reports whether path already holds exactly data.
func fileMatches(path string, data []byte) bool {
	onDisk, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return bytes.Equal(onDisk, data)
}
